name: Release
on:
  push:
    branches:
      - master
permissions:
  contents: write
  pull-requests: write

jobs:
  unit-tests:
    uses: salesforcecli/github-workflows/.github/workflows/unitTest.yml@main
  nuts:
    needs: unit-tests
    uses: salesforcecli/github-workflows/.github/workflows/nut.yml@main
    secrets: inherit
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
      fail-fast: false
    with:
      os: ${{ matrix.os }}
  release-please:
    name: Release Please
    runs-on: ubuntu-latest
    needs: [unit-tests, nuts]
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - name: Release Please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          release-type: node

  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Node
        uses: actions/setup-node@v4.0.1
        with:
          node-version: 22
          cache: npm
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publish to NPM
        run: npm publish --access public --tag latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
